import type { Metadata } from 'next';
import './globals.css';

import { pretendard } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable}`}>
        <div className="layout font-pretendard">{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
